In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_csv("E:/SalesAnalysisExcelPythonSqlPowerBi/sales_raw_500.csv")

In [3]:
df.head()

   Order_ID Order_Date Customer Region  Product  Sales   Cost
0      1001  1/13/2023    Rohit  South   Mobile  23289  19118
1      1002  10/7/2023     Aman   West   Laptop   8905   5593
2      1003  11/5/2023    Rahul  South  Monitor  59987  39959
3      1004  2/19/2024    Rahul  South  Printer  49597  33892
4      1005  1/26/2024   Anjali  North   Laptop  54797  34468

In [4]:
#duplicate removes
df = df.drop_duplicates()

In [5]:
# fix date column
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors = 'coerce')

In [6]:
df = df.dropna(subset=['Order_Date'])

In [7]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[482 rows x 7 columns]

In [8]:
# sale - cost = profit
# from order_date (separate year and month)

In [9]:
df['Profit'] = df['Sales'] - df['Cost']
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month

In [10]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [11]:
df.to_csv('E:/SalesAnalysisExcelPythonSqlPowerBi/sales_cleaned.csv',index=False)

In [12]:
#data -> python + Excel + SQL

In [13]:
import sqlalchemy as sal

engine = sal.create_engine('mysql+pymysql://root:@localhost:3306/SalesAnalysisDB')

# conn = engine.connect()
df.to_sql(name='sales_data', con = engine, if_exists = 'replace', index=False)

482